param_grid = [
    {
        ("app.config", "num-server-rounds"): 50,
        ("app.config", "fraction-fit"): 1,
        ("app.config", "local-epochs"): 1,
        ("app.config", "strategy"): "fed_avg",
        ("app.config", "model_name"): "resnet50",
        ("app.config", "learning-rate-max"): 0.0001,
        ("app.config", "learning-rate-min"): 0.00001,
        ("app.config", "batch_size"): 128,
        ("app.config", "dataset_version"): "resnet_fed_avg_IID_3_channels",
        ("app.config", "data_dir"): "/mnt/fedJam/spectro_flower_all",
        ("app.config", "use_multi_channel_dataset"): False,
        ("app.config", "channels"): 3,
        ("app.config", "num_classes_per_partition"): 4,
        ("app.config", "classes"): 4,
        ("app.config", "fft"): 0,
        ("app.config", "gain"): 0,
        ("app.config", "num_clients"): 10,
        ("app.config", "is_lora"): False,
        ("app.config", "is_timm"): True,
        ("app.config", "is_warmup"): False,
        ("app.config", "seed"): 42,

        ("federations.local-simulation.options", "num-supernodes"): 10,
        ("federations.local-simulation.options.backend.client-resources", "num-cpus"): 25,
        ("federations.local-simulation.options.backend.client-resources", "num-gpus"): 0.25,
    },

    {
        ("app.config", "num-server-rounds"): 50,
        ("app.config", "fraction-fit"): 1,
        ("app.config", "local-epochs"): 1,
        ("app.config", "strategy"): "fed_avg",
        ("app.config", "model_name"): "resnet50",
        ("app.config", "learning-rate-max"): 0.0001,
        ("app.config", "learning-rate-min"): 0.00001,
        ("app.config", "batch_size"): 128,
        ("app.config", "dataset_version"): "resnet_fed_avg_IID_3_channels",
        ("app.config", "data_dir"): "/mnt/fedJam/spectro_flower_all",
        ("app.config", "use_multi_channel_dataset"): False,
        ("app.config", "channels"): 3,
        ("app.config", "num_classes_per_partition"): 4,
        ("app.config", "classes"): 4,
        ("app.config", "fft"): 0,
        ("app.config", "gain"): 0,
        ("app.config", "num_clients"): 25,
        ("app.config", "is_lora"): False,
        ("app.config", "is_timm"): True,
        ("app.config", "is_warmup"): False,
        ("app.config", "seed"): 42,

        ("federations.local-simulation.options", "num-supernodes"): 25,
        ("federations.local-simulation.options.backend.client-resources", "num-cpus"): 25,
        ("federations.local-simulation.options.backend.client-resources", "num-gpus"): 0.25,
    },

    {
        ("app.config", "num-server-rounds"): 50,
        ("app.config", "fraction-fit"): 1,
        ("app.config", "local-epochs"): 1,
        ("app.config", "strategy"): "fed_avg",
        ("app.config", "model_name"): "resnet50",
        ("app.config", "learning-rate-max"): 0.0001,
        ("app.config", "learning-rate-min"): 0.00001,
        ("app.config", "batch_size"): 128,
        ("app.config", "dataset_version"): "resnet_fed_avg_IID_3_channels",
        ("app.config", "data_dir"): "/mnt/fedJam/spectro_flower_all",
        ("app.config", "use_multi_channel_dataset"): False,
        ("app.config", "channels"): 3,
        ("app.config", "num_classes_per_partition"): 4,
        ("app.config", "classes"): 4,
        ("app.config", "fft"): 0,
        ("app.config", "gain"): 0,
        ("app.config", "num_clients"): 50,
        ("app.config", "is_lora"): False,
        ("app.config", "is_timm"): True,
        ("app.config", "is_warmup"): False,
        ("app.config", "seed"): 42,

        ("federations.local-simulation.options", "num-supernodes"): 50,
        ("federations.local-simulation.options.backend.client-resources", "num-cpus"): 25,
        ("federations.local-simulation.options.backend.client-resources", "num-gpus"): 0.25,
    },

    {
        ("app.config", "num-server-rounds"): 50,
        ("app.config", "fraction-fit"): 1,
        ("app.config", "local-epochs"): 1,
        ("app.config", "strategy"): "fed_avg",
        ("app.config", "model_name"): "resnet50",
        ("app.config", "learning-rate-max"): 0.0001,
        ("app.config", "learning-rate-min"): 0.00001,
        ("app.config", "batch_size"): 128,
        ("app.config", "dataset_version"): "resnet_fed_avg_N_IID_3_channels",
        ("app.config", "data_dir"): "/mnt/fedJam/spectro_flower_all",
        ("app.config", "use_multi_channel_dataset"): False,
        ("app.config", "channels"): 3,
        ("app.config", "num_classes_per_partition"): 2,
        ("app.config", "classes"): 4,
        ("app.config", "fft"): 0,
        ("app.config", "gain"): 0,
        ("app.config", "num_clients"): 10,
        ("app.config", "is_lora"): False,
        ("app.config", "is_timm"): True,
        ("app.config", "is_warmup"): False,
        ("app.config", "seed"): 42,

        ("federations.local-simulation.options", "num-supernodes"): 10,
        ("federations.local-simulation.options.backend.client-resources", "num-cpus"): 25,
        ("federations.local-simulation.options.backend.client-resources", "num-gpus"): 0.25,
    },

    {
        ("app.config", "num-server-rounds"): 50,
        ("app.config", "fraction-fit"): 1,
        ("app.config", "local-epochs"): 1,
        ("app.config", "strategy"): "fed_avg",
        ("app.config", "model_name"): "resnet50",
        ("app.config", "learning-rate-max"): 0.0001,
        ("app.config", "learning-rate-min"): 0.00001,
        ("app.config", "batch_size"): 128,
        ("app.config", "dataset_version"): "resnet_fed_avg_N_IID_3_channels",
        ("app.config", "data_dir"): "/mnt/fedJam/spectro_flower_all",
        ("app.config", "use_multi_channel_dataset"): False,
        ("app.config", "channels"): 3,
        ("app.config", "num_classes_per_partition"): 2,
        ("app.config", "classes"): 4,
        ("app.config", "fft"): 0,
        ("app.config", "gain"): 0,
        ("app.config", "num_clients"): 25,
        ("app.config", "is_lora"): False,
        ("app.config", "is_timm"): True,
        ("app.config", "is_warmup"): False,
        ("app.config", "seed"): 42,

        ("federations.local-simulation.options", "num-supernodes"): 25,
        ("federations.local-simulation.options.backend.client-resources", "num-cpus"): 25,
        ("federations.local-simulation.options.backend.client-resources", "num-gpus"): 0.25,
    },

    {
        ("app.config", "num-server-rounds"): 50,
        ("app.config", "fraction-fit"): 1,
        ("app.config", "local-epochs"): 1,
        ("app.config", "strategy"): "fed_avg",
        ("app.config", "model_name"): "resnet50",
        ("app.config", "learning-rate-max"): 0.0001,
        ("app.config", "learning-rate-min"): 0.00001,
        ("app.config", "batch_size"): 128,
        ("app.config", "dataset_version"): "resnet_fed_avg_N_IID_3_channels",
        ("app.config", "data_dir"): "/mnt/fedJam/spectro_flower_all",
        ("app.config", "use_multi_channel_dataset"): False,
        ("app.config", "channels"): 3,
        ("app.config", "num_classes_per_partition"): 2,
        ("app.config", "classes"): 4,
        ("app.config", "fft"): 0,
        ("app.config", "gain"): 0,
        ("app.config", "num_clients"): 50,
        ("app.config", "is_lora"): False,
        ("app.config", "is_timm"): True,
        ("app.config", "is_warmup"): False,
        ("app.config", "seed"): 42,

        ("federations.local-simulation.options", "num-supernodes"): 50,
        ("federations.local-simulation.options.backend.client-resources", "num-cpus"): 25,
        ("federations.local-simulation.options.backend.client-resources", "num-gpus"): 0.25,
    },

    {
        ("app.config", "num-server-rounds"): 50,
        ("app.config", "fraction-fit"): 1,
        ("app.config", "local-epochs"): 1,
        ("app.config", "strategy"): "fed_avg",
        ("app.config", "model_name"): "resnet50",
        ("app.config", "learning-rate-max"): 0.0001,
        ("app.config", "learning-rate-min"): 0.00001,
        ("app.config", "batch_size"): 128,
        ("app.config", "dataset_version"): "resnet_fed_avg_N_IID_3_channels",
        ("app.config", "data_dir"): "/mnt/fedJam/spectro_flower_all",
        ("app.config", "use_multi_channel_dataset"): False,
        ("app.config", "channels"): 3,
        ("app.config", "num_classes_per_partition"): 3,
        ("app.config", "classes"): 4,
        ("app.config", "fft"): 0,
        ("app.config", "gain"): 0,
        ("app.config", "num_clients"): 10,
        ("app.config", "is_lora"): False,
        ("app.config", "is_timm"): True,
        ("app.config", "is_warmup"): False,
        ("app.config", "seed"): 42,

        ("federations.local-simulation.options", "num-supernodes"): 10,
        ("federations.local-simulation.options.backend.client-resources", "num-cpus"): 25,
        ("federations.local-simulation.options.backend.client-resources", "num-gpus"): 0.25,
    },

    {
        ("app.config", "num-server-rounds"): 50,
        ("app.config", "fraction-fit"): 1,
        ("app.config", "local-epochs"): 1,
        ("app.config", "strategy"): "fed_avg",
        ("app.config", "model_name"): "resnet50",
        ("app.config", "learning-rate-max"): 0.0001,
        ("app.config", "learning-rate-min"): 0.00001,
        ("app.config", "batch_size"): 128,
        ("app.config", "dataset_version"): "resnet_fed_avg_N_IID_3_channels",
        ("app.config", "data_dir"): "/mnt/fedJam/spectro_flower_all",
        ("app.config", "use_multi_channel_dataset"): False,
        ("app.config", "channels"): 3,
        ("app.config", "num_classes_per_partition"): 3,
        ("app.config", "classes"): 4,
        ("app.config", "fft"): 0,
        ("app.config", "gain"): 0,
        ("app.config", "num_clients"): 25,
        ("app.config", "is_lora"): False,
        ("app.config", "is_timm"): True,
        ("app.config", "is_warmup"): False,
        ("app.config", "seed"): 42,

        ("federations.local-simulation.options", "num-supernodes"): 25,
        ("federations.local-simulation.options.backend.client-resources", "num-cpus"): 25,
        ("federations.local-simulation.options.backend.client-resources", "num-gpus"): 0.25,
    },

    {
        ("app.config", "num-server-rounds"): 50,
        ("app.config", "fraction-fit"): 1,
        ("app.config", "local-epochs"): 1,
        ("app.config", "strategy"): "fed_avg",
        ("app.config", "model_name"): "resnet50",
        ("app.config", "learning-rate-max"): 0.0001,
        ("app.config", "learning-rate-min"): 0.00001,
        ("app.config", "batch_size"): 128,
        ("app.config", "dataset_version"): "resnet_fed_avg_N_IID_3_channels",
        ("app.config", "data_dir"): "/mnt/fedJam/spectro_flower_all",
        ("app.config", "use_multi_channel_dataset"): False,
        ("app.config", "channels"): 3,
        ("app.config", "num_classes_per_partition"): 3,
        ("app.config", "classes"): 4,
        ("app.config", "fft"): 0,
        ("app.config", "gain"): 0,
        ("app.config", "num_clients"): 50,
        ("app.config", "is_lora"): False,
        ("app.config", "is_timm"): True,
        ("app.config", "is_warmup"): False,
        ("app.config", "seed"): 42,

        ("federations.local-simulation.options", "num-supernodes"): 50,
        ("federations.local-simulation.options.backend.client-resources", "num-cpus"): 25,
        ("federations.local-simulation.options.backend.client-resources", "num-gpus"): 0.25,
    }


]