# === EXPERIMENT CONFIGURATION ===
EXPERIMENT_NAME = "pulse_gain_30_fft_1024"
SPECTROGRAMS_SAMPLES = 1000
FFT_SIZE = 1024

CSV_FILE_APP = f"APP_KPIs/{EXPERIMENT_NAME}.csv"
CSV_FILE_PHY = f"PHY_KPIs/{EXPERIMENT_NAME}.csv"
SPECTROGRAM_FOLDER = f"/home/yale/Desktop/spectrograms/{EXPERIMENT_NAME}"
TIME_INFO_FILE = f"{SPECTROGRAM_FOLDER}/time_info.csv"
KPI_OUTPUT_FOLDER = f"KPI_in_Images/{EXPERIMENT_NAME}"
