[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fedjam-flower"
version = "1.0.0"
description = ""
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.17.0",
    "flwr-datasets[vision]>=0.5.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "fj"

[tool.flwr.app.components]
serverapp = "fedjam_flower.server_app:app"
clientapp = "fedjam_flower.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 50
fraction-fit = 1
local-epochs = 1
strategy = "fed_avg"
model_name = "tiny_vit_5m_224"
learning-rate-max = 0.0002
learning-rate-min = 0.00001
batch_size = 128
dataset_version = "test2"
data_dir = "/mnt/fedJam/spectro_flower_8_channels"
use_multi_channel_dataset = true 
channels = 8
num_classes_per_partition = 4
classes = 4
fft = 0
gain = 0
num_clients = 10
is_lora = false
is_timm = true
is_warmup = false
seed = 42

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 10
options.backend.client-resources.num-cpus = 20
options.backend.client-resources.num-gpus = 0.25
