[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fedjam-flower"
version = "1.0.0"
description = ""
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.17.0",
    "flwr-datasets[vision]>=0.5.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "fj"

[tool.flwr.app.components]
serverapp = "fedjam_flower.server_app:app"
clientapp = "fedjam_flower.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 50
fraction-fit = 1
local-epochs = 1
model_name = "WinKawaks/vit-small-patch16-224"
learning-rate-max = 5e-4
learning-rate-min = 1e-6
batch_size = 128
dataset_version = "dataset_v3"
data_dir = "/home/ioannis/Desktop/spectrograms/dataset_v3/spectro_flower_gain"
fft = 0
gain = 30
num_clients = 10
is_lora = true
is_timm = false
is_warmup = false
random_seed = 42
classes_per_partition = 4 # IID: 4, Non-IID: < 4

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 10
options.backend.client-resources.num-cpus = 10
options.backend.client-resources.num-gpus = 0.3
